//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projetCatalogueProduit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAT_CATEGORIE
    {
        public int CODE_CATEGORIE { get; set; }
        public string LIBELLE_CATEGORIE { get; set; }
        public DateTime DATE_SAISIE { get; set; }
    }
}
